name: upload-to-s3-action

description: Upload files to S3-compatible storage

inputs:
  src-path:
    description: Source directory or file to upload
    required: true
  dest-path:
    description: Destination path in S3 bucket
    required: true
  bucket:
    description: S3 bucket name
    required: true
  endpoint-url:
    description: S3 endpoint URL (e.g., https://storage.yandexcloud.net)
    required: true
  s3-key-id:
    description: S3 access key ID
    required: true
  s3-secret-key:
    description: S3 secret access key
    required: true
  region:
    description: AWS region (default: ru-central1)
    required: true

runs:
  using: composite
  steps:
  - name: Install AWS CLI
    uses: unfor19/install-aws-cli-action@v1
    with:
      version: 2.22.35
      arch: amd64
  - name: Upload to S3
    env:
      AWS_ACCESS_KEY_ID: ${{ inputs.s3-key-id }}
      AWS_SECRET_ACCESS_KEY: ${{ inputs.s3-secret-key }}
      AWS_DEFAULT_REGION: ${{ inputs.region }}
      AWS_EC2_METADATA_DISABLED: true
      AWS_REQUEST_CHECKSUM_CALCULATION: when_required
      AWS_RESPONSE_CHECKSUM_VALIDATION: when_required
    run: |
      aws s3 cp ${{ inputs.src-path }} s3://${{ inputs.bucket }}${{ inputs.dest-path }} --endpoint-url=${{ inputs.endpoint-url }} --recursive
    shell: bash

